apiVersion: batch/v1
kind: Job
metadata:
  name: encoder-outcome-prediction-multitask-hosp-agent
  labels:
    app: encoder-outcome-prediction
    sweep: multitask-hosp
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: encoder-outcome-prediction
        sweep: multitask-hosp
    spec:
      containers:
        - name: encoder-outcome-prediction
          image: registry.datexis.com/tsteffek/encoderoutcomeprediction:multitask-PMBv2
          workingDir: /workspace/EncoderOutcomePrediction
          command: [
              "wandb", "agent",
              "s90444-berliner-hochschule-f-r-technik/EncoderOutcomePred/g6kw3wzg"
          ]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/model-pvc/huggingface_cache"
            - name: WANDB_AGENT_RUN_DIR
              value: "/workspace/EncoderOutcomePrediction"
            - name: WANDB_ENTITY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: entity
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api_key
            - name: WANDB_DIR
              value: "/model-pvc/wandb"
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: data-pvc
              mountPath: /data-pvc
            - name: model-pvc
              mountPath: /model-pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: eod-pvc
        - name: model-pvc
          persistentVolumeClaim:
            claimName: large-eod-model-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never