apiVersion: batch/v1
kind: Job
metadata:
  name: encoder-outcome-prediction-multitask-icu
  labels:
    app: encoder-outcome-prediction
spec:
  template:
    metadata:
      labels:
        app: encoder-outcome-prediction
    spec:
      containers:
        - name: encoder-outcome-prediction
          workingDir: /workspace/EncoderOutcomePrediction
          image: registry.datexis.com/tsteffek/encoderoutcomeprediction:multitask-PMBv2
          imagePullPolicy: Always
          command:
            - "python"
            - "src/classification_main.py"
            - "fit"
            
            - "--config=src/config_multitask_icu.yaml"
            
            - "--trainer.default_root_dir=/model-pvc/multitask-icu"
             
            - "--data.multitask=true"

            - "--data.icd9_data_dir=/data-pvc/data/mimic-iv/icd9/icu/"
            - "--data.icd10_data_dir=/data-pvc/data/mimic-iv/icd10/icu/"

            - "--data.truncate_again=True"
            - "--data.pretrained_model=microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract"
          env:
            - name: PL_DISABLE_FSWATCHER
              value: "1"
            - name: PYTORCH_NUM_WORKERS
              value: "8"
            - name: LANG
              value: 'C.UTF-8'
            - name: TOKENIZERS_PARALLELISM
              value: 'true'
            - name: NCCL_DEBUG
              value: 'INFO'
            - name: HF_HOME
              value: "/model-pvc/huggingface_cache"
            - name: WANDB_ENTITY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: entity
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb
                  key: api_key
          resources:
            requests:
              cpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: data-pvc
              mountPath: /data-pvc
            - name: model-pvc
              mountPath: /model-pvc
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: a100
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: eod-pvc
        - name: model-pvc
          persistentVolumeClaim:
            claimName: large-eod-model-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never